-- Seed: the first three PlayThruu News stories (30 Sept 2026), moved from
-- the old content/news/*.json files. Run once, after 2026-09-30_news.sql.

insert into public.news_articles (slug, title, summary, body, why_it_matters, category, importance, status, lifecycle, verification_status, confidence_level, confidence_reason, primary_source, first_reported_by, sources, game, developer, publisher, platforms, genres, tags, seo_title, seo_description, keywords, social_caption, card_description, published_at, updated_at, last_checked_at) values (
  'castlevania-40th-anniversary-free-mobile',
  'Konami marks 40 years of Castlevania by making the original free on mobile',
  'The 1986 Castlevania is free on iOS and Android until October 24, and anyone who downloads it during that window can keep it. An anniversary video has fans hoping for a 3D collection, but Konami hasn''t announced one.',
  '[{"type":"p","text":"Castlevania turned 40 on September 26, the anniversary of the original game''s 1986 Famicom release. Konami announced on September 25 that it was celebrating by giving away the game that started the series."},{"type":"h2","text":"The free game"},{"type":"p","text":"The mobile port of the first Castlevania is free on the Apple App Store and Google Play until October 24. If you download it before then, you keep it: Konami says it can still be redownloaded and played after the promotion ends. Reports disagree on the exact cutoff time, so it''s safest to grab it before October 24 wherever you are."},{"type":"p","text":"According to Push Square, this is the full game with no ads or in-app purchases, it works offline, and it takes up only around 6MB."},{"type":"h2","text":"The retro sale"},{"type":"p","text":"There''s also a discount on PC. TheGamer reports that the Castlevania Anniversary Collection is 80% off on Steam, bringing it down to $3.99. The bundle contains classic entries from the original game through Castlevania: Bloodlines, plus Kid Dracula and a digital history-of-the-series book."},{"type":"h2","text":"About that 3D collection"},{"type":"status","label":"Rumor","text":"Konami''s anniversary video ends with Simon Belmont walking past four portraits that show artwork from Belmont''s Curse, Lament of Innocence, Curse of Darkness and the first Lords of Shadow. Fans read this as a hint that a compilation of 3D Castlevania games is coming. Konami has announced nothing, and outlets including GameSpot and Time Extension describe it as speculation. It''s possible the artwork was simply chosen for how it looks."},{"type":"p","text":"The hope isn''t unreasonable. The series'' 3D entries, from the Nintendo 64 games to the PS2 duo and the Lords of Shadow trilogy, have mostly stayed tied to their original hardware, while the 2D games have been re-released several times. Until Konami confirms something, though, it remains a hope."}]'::jsonb,
  'It''s a free, permanent copy of a genuinely important game, and it takes about a minute to claim. The 3D collection is worth watching for, but don''t count on it until Konami says so.',
  'Deals',
  'standard',
  'published',
  'published',
  'confirmed',
  'High',
  'High for the free game and its terms, which come from Konami and match across outlets. Low for the 3D collection, which is fan speculation based on a video with no announcement. The exact cutoff time and the sale details come from individual reports.',
  'Konami announcement',
  null,
  '[{"name":"Konami announcement (via Inven Global)","url":"https://www.invenglobal.com/articles/26484/original-castlevania-available-free-until-october-24-for-series-40th-anniversary","tier":1},{"name":"Push Square","url":"https://www.pushsquare.com/news/2026/09/enjoy-1986s-castlevania-for-free-on-your-phone-for-40th-anniversary","tier":2},{"name":"TheGamer","url":"https://www.thegamer.com/castlevania-nes-free-40th-anniversary/","tier":2},{"name":"VGC","url":"https://www.videogameschronicle.com/news/konami-is-celebrating-the-40th-anniversary-of-castlevania-with-a-big-retro-sale-and-a-free-game/","tier":2},{"name":"GameSpot","url":"https://www.gamespot.com/articles/castlevania-turns-40-and-konami-may-have-just-teased-a-3d-collection/","tier":2},{"name":"Time Extension","url":"https://www.timeextension.com/news/2026/09/a-new-castlevania-40th-anniversary-video-has-released-and-fans-think-they-have-spotted-a-tease-for-a-3d-collection","tier":2}]'::jsonb,
  'Castlevania',
  'Konami',
  'Konami',
  array['iOS','Android']::text[],
  array['Action','Platformer']::text[],
  array['free game','anniversary','sale']::text[],
  'Original Castlevania Free on iOS and Android for 40th Anniversary',
  'Konami is giving away the original 1986 Castlevania on iOS and Android until October 24 for the series'' 40th anniversary, and you keep it after the offer ends.',
  array['Castlevania free','Castlevania 40th anniversary','Castlevania mobile','Konami','Castlevania 3D collection','Castlevania Anniversary Collection sale','free mobile games']::text[],
  'Castlevania is 40, and the 1986 original is free on iOS and Android until October 24. Download it before then and it''s yours to keep.',
  'The 1986 original is free on iOS and Android until Oct 24, and you keep it once downloaded.',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z'
);

insert into public.news_articles (slug, title, summary, body, why_it_matters, category, importance, status, lifecycle, verification_status, confidence_level, confidence_reason, primary_source, first_reported_by, sources, game, developer, publisher, platforms, genres, tags, seo_title, seo_description, keywords, social_caption, card_description, published_at, updated_at, last_checked_at) values (
  'marvels-wolverine-scent-trail-toggle',
  'Marvel''s Wolverine patch lets you switch off the collectible scent trails',
  'Insomniac''s update 1.001.006 for Marvel''s Wolverine adds settings to turn off the scent trails, audio cues and root markers that point you to optional collectibles. Players have criticised that guidance since the game''s September 15 launch.',
  '[{"type":"p","text":"Two weeks after launch, Insomniac Games has given Marvel''s Wolverine players the option many of them asked for: turning off most of the on-screen guidance that points to collectibles. The PS5 update, version 1.001.006, went out over the weekend. Reports date it to September 26, with some outlets covering it a day or two later."},{"type":"h2","text":"What you can now turn off"},{"type":"p","text":"A new Senses section under Settings, then Gameplay, has three separate toggles: Whisky Bottle Scent Trails, Material Crate Audio Clues and Nightmare Door Roots. Each one controls a different optional hint system, so you can keep any you find useful and disable the rest."},{"type":"h2","text":"The fine print"},{"type":"p","text":"The switches only apply to optional content. Senses that the story depends on still appear. Insomniac''s notes give the example of tracking Red during the mission The One That Got Away. If you equip the Whisky Finder or Crate Finder Adaptations, those override your settings and bring back the matching cues."},{"type":"h2","text":"How we got here"},{"type":"p","text":"Since release, the scent trails have been the game''s most-discussed complaint, with players arguing they made exploration feel too guided. An earlier update toned the effect down. As reported by GamesRadar+, Insomniac said at the time that it was looking into toggleable options, and this patch delivers them."},{"type":"h2","text":"Also fixed"},{"type":"p","text":"The update also fixes a number of crashes, a bug that could leave you stuck while sliding down a tree in The One That Got Away, Wolverine''s claws being misaligned in Photo Mode, objects turning white after long play sessions, and a doubled-up bathroom sign in the casino."}]'::jsonb,
  'If the constant guidance put you off exploring Wolverine''s world, you can now find collectibles on your own terms without losing the story cues. It''s also a quick response to feedback from a major first-party studio, finished within two weeks of launch.',
  'Update',
  'standard',
  'published',
  'published',
  'confirmed',
  'High',
  'Several outlets reproduced the same official patch notes, and their accounts match. The exact release day is slightly less certain: reports place it between September 26 and 28.',
  'Insomniac Games update notes',
  'GamesRadar+ (earlier Insomniac comments on toggle options)',
  '[{"name":"Insomniac Games update notes (support site)","url":"https://support.insomniac.games/hc/en-us/sections/55420144191763-Game-Updates","tier":1},{"name":"PlayStation Universe","url":"https://www.psu.com/news/marvels-wolverine-update-1-001-006-adds-option-to-turn-off-sense-trails-fixes-crashes-full-patch-notes-listed/","tier":2},{"name":"Game Rant","url":"https://gamerant.com/marvels-wolverine-update-scent-trail-toggle-patch-notes/","tier":2},{"name":"GamesRadar+","url":"https://www.gamesradar.com/games/action/new-marvels-wolverine-update-makes-the-games-infamous-scent-trails-less-intense-while-insomniac-explores-toggleable-options/","tier":2},{"name":"Push Square","url":"https://www.pushsquare.com/news/2026/09/newest-wolverine-ps5-update-wipes-out-scent-trails-to-collectibles","tier":2}]'::jsonb,
  'Marvel''s Wolverine',
  'Insomniac Games',
  'Sony Interactive Entertainment',
  array['PS5']::text[],
  array['Action']::text[],
  array['patch','accessibility options']::text[],
  'Marvel''s Wolverine Update 1.001.006 Adds Scent Trail Toggles',
  'Marvel''s Wolverine update 1.001.006 lets PS5 players turn off collectible scent trails, audio clues and Nightmare Door roots, and fixes crashes and bugs too.',
  array['Marvel''s Wolverine update','Wolverine 1.001.006','Wolverine scent trails','Insomniac Games','Wolverine patch notes','PS5']::text[],
  'Marvel''s Wolverine''s scent trails can now be turned off. Patch 1.001.006 adds separate toggles for collectible hints, and story cues stay on.',
  'Patch 1.001.006 adds toggles for the collectible scent trails players kept complaining about.',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z'
);

insert into public.news_articles (slug, title, summary, body, why_it_matters, category, importance, status, lifecycle, verification_status, confidence_level, confidence_reason, primary_source, first_reported_by, sources, game, developer, publisher, platforms, genres, tags, seo_title, seo_description, keywords, social_caption, card_description, published_at, updated_at, last_checked_at) values (
  'witcher-3-remastered-free-upgrade',
  'The Witcher 3 Remastered is out now, and most existing owners pay nothing',
  'CD Projekt Red released The Witcher 3: Wild Hunt — Remastered on September 29 as a free upgrade for current owners on PC, PS5, Xbox Series X|S and Switch 2. It bundles both expansions and sets the stage for a new one, Songs of the Past, in 2027.',
  '[{"type":"p","text":"Eleven years after launch, Geralt''s biggest adventure has been given another full pass. The Witcher 3: Wild Hunt — Remastered went live on September 29, and CD Projekt Red is handing it to most existing players for free rather than selling it as a separate product."},{"type":"h2","text":"Who gets it for free"},{"type":"p","text":"If you already own The Witcher 3 on GOG, Steam, the Epic Games Store, PS5 or Xbox Series X|S, the Remastered version is a free upgrade. On Nintendo''s side, Switch 2 players qualify if they own the original Switch version."},{"type":"p","text":"New players can also buy it on Battle.net and the Microsoft Store, where it''s an Xbox Play Anywhere title. CD Projekt Red''s announcement doesn''t list a price. According to the studio, the Remastered edition includes both expansions, Hearts of Stone and Blood and Wine."},{"type":"h2","text":"What''s actually different"},{"type":"p","text":"The upgrade goes further than sharper textures, though those are here too: environments, characters and monsters all get higher-detail assets, alongside reworked foliage and lighting. PC players get a path tracing option. On PS5 Pro, the game uses Sony''s PSSR upscaling, with a ray-traced mode targeting 60fps and a performance mode that reaches up to 90fps."},{"type":"p","text":"The bigger changes are to how it plays. CD Projekt Red has rebuilt the skill system and rebalanced abilities, so long-standing character builds may not work the way they used to. Combat gets new animations and finishers plus an adaptive camera, movement and traversal animations have been overhauled, and the menus have been redesigned."},{"type":"p","text":"Mods are now cross-platform through mod.io integration, which means console players can finally get at some of the community work that used to be PC-only. The Switch 2 version adds motion controls, gyro aiming, mouse support and touchscreen input."},{"type":"h2","text":"What''s next"},{"type":"p","text":"CD Projekt Red is positioning the remaster as the base for Songs of the Past, a new Witcher 3 expansion due in 2027. The announcement doesn''t give further details about the expansion, and it doesn''t say whether the pre-remaster version will stay available. That could matter to players running large PC mod setups."}]'::jsonb,
  'Most people who own The Witcher 3 can now get an upgraded version without paying again. The skill rework and cross-platform mods make it feel noticeably different, not just better-looking, and with Songs of the Past confirmed for 2027, now is a sensible time to return to a save or start a new playthrough.',
  'Release',
  'important',
  'published',
  'published',
  'confirmed',
  'High',
  'Every key detail — date, platforms, eligibility and features — comes directly from CD Projekt Red''s own announcement.',
  'CD PROJEKT RED press release',
  null,
  '[{"name":"CD PROJEKT RED press release","url":"https://press.cdprojektred.com/en/news/1874/the-witcher-3-wild-hunt-remastered-available-now","tier":1},{"name":"XboxAchievements.com","url":"https://www.xboxachievements.com/news/the-witcher-3-wild-hunt-remastered-free-update-now-available/","tier":2},{"name":"GamerBolt weekly news roundup","tier":2}]'::jsonb,
  'The Witcher 3: Wild Hunt',
  'CD PROJEKT RED',
  'CD PROJEKT',
  array['PC','PS5','Xbox Series X|S','Nintendo Switch 2']::text[],
  array['RPG']::text[],
  array['remaster','free upgrade']::text[],
  'The Witcher 3 Remastered: Free Upgrade, Platforms and What''s New',
  'The Witcher 3: Wild Hunt Remastered is out now as a free upgrade on PC, PS5, Xbox Series X|S and Switch 2, with a new skill system and cross-platform mods.',
  array['The Witcher 3 Remastered','Witcher 3 free upgrade','CD Projekt Red','Songs of the Past','Witcher 3 Switch 2','Witcher 3 PS5 Pro','Witcher 3 mods console']::text[],
  'The Witcher 3 Remastered is out now, and if you already own the game, it''s free. Expect a reworked skill system, console mods and path tracing on PC.',
  'Free for existing owners: new skill system, cross-platform mods, and both expansions included.',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z',
  '2026-09-30T09:00:00Z'
);

